openapi: 3.1.1

info:
  title: OpenAPI Express
  version: 1.0.0
  description: API First

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /hello:
    get:
      summary: Hello World
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"
