openapi: 3.1.1

info:
  title: OpenAPI Express Platzi
  version: 1.0.0
  description: API First

servers:
  - url: http://localhost:4000
    description: Local server

components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
    HelloRootResponse:
      type: object
      properties:
        message:
          type: string

paths:
  /:
    get:
      summary: Hello Jose
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"
  /hello:
    get:
      summary: Hello World
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloRootResponse"
  /users:
    post:
      summary: crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - age
                - email
              properties:
                name:
                  type: string
                  minLength: 2
                age:
                  type: integer
                  minimum: 18
                email:
                  type: string
                  format: email
      responses:
        "201":
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  age:
                    type: integer
                  email:
                    type: string
