openapi: 3.1.1

info:
  title: OpenAPI Express Platzi
  version: 1.0.0
  description: API First

servers:
  - url: http://localhost:4000
    description: Local server

paths:
  /hello:
    get:
      summary: Hello World
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"
  /:
    get:
      summary: Hello Jose
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"

components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
    HelloRootResponse:
      type: object
      properties:
        message:
          type: string
